# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
use_frameworks!

def shared_pods
  pod 'Alamofire'
  pod 'SwiftyJSON'
end

target 'WatchLoginAuthenticationThroughiPhone' do
  shared_pods
end

target 'WatchApp Extension' do
  platform:watchos, '2.0'
  shared_pods
end


